In [26]:
import torch
import numpy as np

## 1D

In [3]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [4]:
t.dim() #rank

1

In [5]:
t.shape

torch.Size([7])

## 2D

In [9]:
t = torch.IntTensor([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
    ])
t

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)

In [10]:
t.dim()

2

In [11]:
t.size()

torch.Size([4, 3])

In [12]:
t[:, 1:2]

tensor([[ 2],
        [ 5],
        [ 8],
        [11]], dtype=torch.int32)

## Broadcasting

In [14]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
m1 + m2

tensor([[4., 5.]])

In [15]:
m1 = torch.FloatTensor([[1,2]]) # (1,2)
m2 = torch.FloatTensor([[3],[4]]) # (2,1)
print(m1.matmul(m2)) # (1,1)
print(m1 + m2) # (2,2)

tensor([[11.]])
tensor([[4., 5.],
        [5., 6.]])


In [16]:
m1 = torch.FloatTensor([
    [1,2],
    [3,4]]) # (2,2)
m2 = torch.FloatTensor([
    [1],
    [2]]) # (2,1)

print(m1.matmul(m2)) # matrix mul: (2,1)
print(m1.mul(m2)) # element-wise: (2,2) (after broadcasting)

tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


In [17]:
m1.mean()

tensor(2.5000)

In [18]:
m1.mean(dim=0)
# remove first rank (0, row)
# (2,2) -> (1,2) = (2,)

tensor([2., 3.])

In [19]:
m1.mean(dim=1)
# remove second rank (1, col)
# (2,2) -> (2,1)

tensor([1.5000, 3.5000])

In [20]:
m1.sum(dim=0)

tensor([4., 6.])

In [22]:
m1.argmax(dim=1) # idx of max(dim=1)=[2, 4]

tensor([1, 1])

In [23]:
m1.max(dim=1)

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

## View

In [24]:
# 원소 수를 유지하면서 텐서 크기 변경 (Reshape in Numpy)

In [27]:
t = np.array([
    [[0,1,2],
     [3,4,5]],
    [[6,7,8],
     [9,10,11]]
])
ft = torch.FloatTensor(t)
ft

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [29]:
ft.size()

torch.Size([2, 2, 3])