In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 8.5761e-33],
        [1.4013e-45, 0.0000e+00, 0.0000e+00],
        [1.3497e+25, 4.5827e-41, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
x

tensor([[0.3550, 0.0808, 0.9240],
        [0.1304, 0.1798, 0.8085],
        [0.1114, 0.9572, 0.6454],
        [0.8933, 0.4350, 0.8850],
        [0.4831, 0.3920, 0.5194]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.5930,  1.8191,  0.1328],
        [ 0.3401,  0.4897,  0.3413],
        [-1.0140, -0.8153,  0.2566],
        [ 1.1493, -0.4904, -0.5605],
        [-0.6284,  0.7728, -0.5691]])


In [9]:
x.size()

torch.Size([5, 3])

## Operations

In [10]:
y = torch.rand(5, 3)
x + y

tensor([[-0.1037,  2.6056,  0.3628],
        [ 1.2562,  0.7909,  1.3029],
        [-0.6209,  0.0376,  0.6143],
        [ 2.0675, -0.3319,  0.3335],
        [-0.3342,  0.8885, -0.1283]])

In [11]:
torch.add(x, y)

tensor([[-0.1037,  2.6056,  0.3628],
        [ 1.2562,  0.7909,  1.3029],
        [-0.6209,  0.0376,  0.6143],
        [ 2.0675, -0.3319,  0.3335],
        [-0.3342,  0.8885, -0.1283]])

In [13]:
res = torch.empty(5, 3)
torch.add(x, y, out=res)
res

tensor([[-0.1037,  2.6056,  0.3628],
        [ 1.2562,  0.7909,  1.3029],
        [-0.6209,  0.0376,  0.6143],
        [ 2.0675, -0.3319,  0.3335],
        [-0.3342,  0.8885, -0.1283]])

In [14]:
# in-place
y.add_(x)
y

tensor([[-0.1037,  2.6056,  0.3628],
        [ 1.2562,  0.7909,  1.3029],
        [-0.6209,  0.0376,  0.6143],
        [ 2.0675, -0.3319,  0.3335],
        [-0.3342,  0.8885, -0.1283]])

In [15]:
# reshape
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0560])
0.055981963872909546


## NumPy 변환(Bridge)

In [17]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [18]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

In [30]:
device = torch.device("cpu")
y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
print(z)
print(z.to("cpu", torch.double))

tensor([1.0560])
tensor([1.0560], dtype=torch.float64)
